name: Profile Content Update

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    # Runs at 4am JST
    - cron: '20 19 * * *'

jobs:
  refresh:
    name: Update profile data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Update bio table
        uses: yutkat/bio2markdown-table@v2

      - name: Generate Follower History
        uses: yutkat/github-follower-history@v1
        with:
          country: japan
          username: yutkat
          output-csv: /tmp/follower_history.csv
          target-file: README.md
          start-date: 2023-06-17
          max-labels: 15

      - name: Fetch followed ranking
        run: >
          curl -s https://raw.githubusercontent.com/gayanvoice/top-github-users/main/cache/japan.json |
          jq 'to_entries | .[] | select(.value.login == "yutkat")' |
          jq '.key += 1' > assets/github-followed-ranking.json

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-followed-ranking
          path: assets/github-followed-ranking.json

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit & Push
        if: steps.diff.outcome == 'failure'
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'generated'
          git push
